version: '3.5'

services:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-mongo
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
